In [1]:
#importing relavet libs
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#loading spesific dataset
from datasets import load_dataset
dataset = load_dataset('lukebarousse/data_jobs')

#changing to data frame
df = dataset['train'].to_pandas()

#cleaning data
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [ ]:
#      coulmn          row
#        ^              ^
#df.loc[X:X, name_of_row:name_of_row] 
df.loc[1:11, 'job_title':'job_posted_date']

,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date
1,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07
2,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55
3,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41
4,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36
5,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59
6,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18
7,Data Engineer,Anywhere,via LinkedIn,Full-time,True,Romania,2023-12-07 13:40:49
8,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06-05 13:44:34
9,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57
10,Erfahrene*r Data Engineer*in (m/w/d),"Basel, Switzerland",via LinkedIn,Full-time,False,Switzerland,2023-04-17 13:27:32
11,Data Engineer,"Colorado Springs, CO (+3 others)",via The Muse,Full-time,False,"Texas, United States",2023-11-03 13:06:51

In [9]:
#      coulmn row
#         ^    ^
#df.iloc[X:X, X:X]
df.iloc[1:11, 1:8]

,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date
1,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07
2,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55
3,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41
4,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36
5,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59
6,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18
7,Data Engineer,Anywhere,via LinkedIn,Full-time,True,Romania,2023-12-07 13:40:49
8,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06-05 13:44:34
9,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57
10,Erfahrene*r Data Engineer*in (m/w/d),"Basel, Switzerland",via LinkedIn,Full-time,False,Switzerland,2023-04-17 13:27:32

**same rusalte with diffrent fuctions**

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

In [14]:
salary_year_median = df['salary_year_avg'].median()
salary_hour_median = df['salary_hour_avg'].median()

print(salary_year_median)
print(salary_hour_median)

45.97999954223633
115000.0

In [18]:
df_fill = df

df_fill['salary_year_avg'] = df_fill['salary_year_avg'].fillna(salary_year_median)
df_fill['salary_hour_avg'] = df_fill['salary_hour_avg'].fillna(salary_hour_median)

In [23]:
df_uniqe = df_fill

df_uniqe = df_uniqe.drop_duplicates()

df_uniqe = df_uniqe.drop_duplicates(subset=['job_title', 'company_name', 'job_work_from_home', 'job_location'])

print('length before: ', len(df_fill))
print('length after: ', len(df_uniqe))
print('coulmns removed: ', len(df_fill)-len(df_uniqe))

length before:  785741
length after:  618884
coulmns removed:  166857